# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

DeviceManufacturer.create(id: 1, device_manu_name: 'Samsung')
DeviceManufacturer.create(id: 2, device_manu_name: 'LG')
DeviceManufacturer.create(id: 3, device_manu_name: 'Motorola')
DeviceManufacturer.create(id: 4, device_manu_name: 'ZTE')
DeviceManufacturer.create(id: 5, device_manu_name: 'HTC')
DeviceManufacturer.create(id: 6, device_manu_name: 'Nokia')
DeviceManufacturer.create(id: 7, device_manu_name: 'Apple')

DeviceComponentStatus.create(id: 1, device_comp_status: 'In Stock')
DeviceComponentStatus.create(id: 2, device_comp_status: 'Out of Stock')
DeviceComponentStatus.create(id: 3, device_comp_status: 'Ordered')
DeviceComponentStatus.create(id: 4, device_comp_status: 'Delivered')
DeviceComponentStatus.create(id: 5, device_comp_status: 'Back Ordered')

TechnicianStatus.create(id: 1, tech_status: 'Active')
TechnicianStatus.create(id: 2, tech_status: 'Inactive')
TechnicianStatus.create(id: 3, tech_status: 'On Leave')
TechnicianStatus.create(id: 4, tech_status: 'Sick Day')


DeviceVersion.create(id: 1, device_version_name: 'iPhone 6S/6S Plus', device_manufacturer_id: 7)
DeviceVersion.create(id: 2, device_version_name: 'iPhone 8/8 Plus', device_manufacturer_id: 7)
DeviceVersion.create(id: 3, device_version_name: 'iPhone 7/7 Plus', device_manufacturer_id: 7)
DeviceVersion.create(id: 4, device_version_name: 'iPhone SE', device_manufacturer_id: 7)
DeviceVersion.create(id: 5, device_version_name: 'iPhone 6S/6S Plus', device_manufacturer_id: 7)
DeviceVersion.create(id: 6, device_version_name: 'Galaxy S9/S9 Plus', device_manufacturer_id: 1)
DeviceVersion.create(id: 7, device_version_name: 'Galaxy Note 8', device_manufacturer_id: 1)
DeviceVersion.create(id: 8, device_version_name: 'Galaxy S8 Active', device_manufacturer_id: 1)
DeviceVersion.create(id: 9, device_version_name: 'Galaxy S8/Se Plus', device_manufacturer_id: 1)
DeviceVersion.create(id: 10, device_version_name: 'Galaxy Note 7', device_manufacturer_id: 1)
DeviceVersion.create(id: 11, device_version_name: 'Galaxy S7 Active', device_manufacturer_id: 1)
DeviceVersion.create(id: 12, device_version_name: 'Galaxy S7', device_manufacturer_id: 1)
DeviceVersion.create(id: 13, device_version_name: 'Galaxy S6', device_manufacturer_id: 1)
DeviceVersion.create(id: 14, device_version_name: 'V35 ThinQ', device_manufacturer_id: 2)
DeviceVersion.create(id: 15, device_version_name: 'G7 ThinQ', device_manufacturer_id: 2)
DeviceVersion.create(id: 16, device_version_name: 'Stylo 4', device_manufacturer_id: 2)
DeviceVersion.create(id: 17, device_version_name: 'V30', device_manufacturer_id: 2)
DeviceVersion.create(id: 18, device_version_name: 'Moto E4/E4 Plus', device_manufacturer_id: 3)
DeviceVersion.create(id: 19, device_version_name: 'Moto G5/G5 Plus', device_manufacturer_id: 3)
DeviceVersion.create(id: 20, device_version_name: 'Moto G5S/G5S Plus', device_manufacturer_id: 3)
DeviceVersion.create(id: 21, device_version_name: 'Moto X4', device_manufacturer_id: 3)
DeviceVersion.create(id: 22, device_version_name: '6.1', device_manufacturer_id: 6)
DeviceVersion.create(id: 23, device_version_name: '3310', device_manufacturer_id: 6)
DeviceVersion.create(id: 24, device_version_name: 'Lumina', device_manufacturer_id: 6)
DeviceVersion.create(id: 25, device_version_name: 'ZFive', device_manufacturer_id: 4)
DeviceVersion.create(id: 26, device_version_name: 'Blade', device_manufacturer_id: 4)
DeviceVersion.create(id: 27, device_version_name: 'Tempo X', device_manufacturer_id: 4)
DeviceVersion.create(id: 28, device_version_name: 'U12 Plus', device_manufacturer_id: 5)
DeviceVersion.create(id: 29, device_version_name: 'Desire 12/12 Plus', device_manufacturer_id: 5)
DeviceVersion.create(id: 30, device_version_name: 'U11/11 Plus', device_manufacturer_id: 5)

# add two attributes
DeviceComponent.create(id: 1, device_version_id: 1, device_comp_name: 'Screen display', device_comp_color: 'Black', device_comp_description: 'Touch screen component.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 2, device_version_id: 1, device_comp_name: 'Battery', device_comp_color: 'Black', device_comp_description: 'Source of power for the device.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 3, device_version_id: 1, device_comp_name: 'System-on-a-Chip', device_comp_color: 'Black', device_comp_description: 'Processor that brings CPU and MODEM together.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 4, device_version_id: 1, device_comp_name: 'Memory card', device_comp_color: 'Black', device_comp_description: 'Stores memory on a device.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 5, device_version_id: 1, device_comp_name: 'Modem', device_comp_color: 'Black', device_comp_description: 'Communication component for receiving texts and calls.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 6, device_version_id: 1, device_comp_name: 'Camera', device_comp_color: 'Black', device_comp_description: 'Captures photographs and video.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 7, device_version_id: 1, device_comp_name: 'Sensor', device_comp_color: 'Black', device_comp_description: 'Enables touch-screen ability.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 8, device_version_id: 1, device_comp_name: 'Processor', device_comp_color: 'Black', device_comp_description: 'Processes basic instructions that drive the device.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 9, device_version_id: 6, device_comp_name: 'Screen display', device_comp_color: 'Black', device_comp_description: 'Touch screen component.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 10, device_version_id: 6, device_comp_name: 'Battery', device_comp_color: 'Black', device_comp_description: 'Source of power for the device.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 11, device_version_id: 6, device_comp_name: 'System-on-a-Chip', device_comp_color: 'Black', device_comp_description: 'Processor that brings CPU and MODEM together.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 12, device_version_id: 6, device_comp_name: 'Memory card', device_comp_color: 'Black', device_comp_description: 'Stores memory on a device.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 13, device_version_id: 6, device_comp_name: 'Modem', device_comp_color: 'Black', device_comp_description: 'Communication component for receiving texts and calls.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 14, device_version_id: 6, device_comp_name: 'Camera', device_comp_color: 'Black', device_comp_description: 'Captures photographs and video.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 15, device_version_id: 6, device_comp_name: 'Sensor', device_comp_color: 'Black', device_comp_description: 'Enables touch-screen ability.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 16, device_version_id: 6, device_comp_name: 'Processor', device_comp_color: 'Black', device_comp_description: 'Processes basic instructions that drive the device.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 17, device_version_id: 18, device_comp_name: 'Screen display', device_comp_color: 'Black', device_comp_description: 'Touch screen component.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 18, device_version_id: 18, device_comp_name: 'Battery', device_comp_color: 'Black', device_comp_description: 'Source of power for the device.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 19, device_version_id: 18, device_comp_name: 'System-on-a-Chip', device_comp_color: 'Black', device_comp_description: 'Processor that brings CPU and MODEM together.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 20, device_version_id: 18, device_comp_name: 'Memory card', device_comp_color: 'Black', device_comp_description: 'Stores memory on a device.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 21, device_version_id: 18, device_comp_name: 'Modem', device_comp_color: 'Black', device_comp_description: 'Communication component for receiving texts and calls.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 22, device_version_id: 18, device_comp_name: 'Camera', device_comp_color: 'Black', device_comp_description: 'Captures photographs and video.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 23, device_version_id: 18, device_comp_name: 'Sensor', device_comp_color: 'Black', device_comp_description: 'Enables touch-screen ability.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 24, device_version_id: 18, device_comp_name: 'Processor', device_comp_color: 'Black', device_comp_description: 'Processes basic instructions that drive the device.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 25, device_version_id: 22, device_comp_name: 'Screen display', device_comp_color: 'Black', device_comp_description: 'Touch screen component.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 26, device_version_id: 22, device_comp_name: 'Battery', device_comp_color: 'Black', device_comp_description: 'Source of power for the device.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 27, device_version_id: 22, device_comp_name: 'System-on-a-Chip', device_comp_color: 'Black', device_comp_description: 'Processor that brings CPU and MODEM together.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 28, device_version_id: 22, device_comp_name: 'Memory card', device_comp_color: 'Black', device_comp_description: 'Stores memory on a device.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 29, device_version_id: 22, device_comp_name: 'Modem', device_comp_color: 'Black', device_comp_description: 'Communication component for receiving texts and calls.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 30, device_version_id: 22, device_comp_name: 'Camera', device_comp_color: 'Black', device_comp_description: 'Captures photographs and video.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 31, device_version_id: 22, device_comp_name: 'Sensor', device_comp_color: 'Black', device_comp_description: 'Enables touch-screen ability.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 32, device_version_id: 22, device_comp_name: 'Processor', device_comp_color: 'Black', device_comp_description: 'Processes basic instructions that drive the device.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 33, device_version_id: 25, device_comp_name: 'Screen display', device_comp_color: 'Black', device_comp_description: 'Touch screen component.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 34, device_version_id: 25, device_comp_name: 'Battery', device_comp_color: 'Black', device_comp_description: 'Source of power for the device.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 35, device_version_id: 25, device_comp_name: 'System-on-a-Chip', device_comp_color: 'Black', device_comp_description: 'Processor that brings CPU and MODEM together.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 36, device_version_id: 25, device_comp_name: 'Memory card', device_comp_color: 'Black', device_comp_description: 'Stores memory on a device.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 37, device_version_id: 25, device_comp_name: 'Modem', device_comp_color: 'Black', device_comp_description: 'Communication component for receiving texts and calls.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 38, device_version_id: 25, device_comp_name: 'Camera', device_comp_color: 'Black', device_comp_description: 'Captures photographs and video.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 39, device_version_id: 25, device_comp_name: 'Sensor', device_comp_color: 'Black', device_comp_description: 'Enables touch-screen ability.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 40, device_version_id: 25, device_comp_name: 'Processor', device_comp_color: 'Black', device_comp_description: 'Processes basic instructions that drive the device.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 41, device_version_id: 28, device_comp_name: 'Screen display', device_comp_color: 'Black', device_comp_description: 'Touch screen component.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 42, device_version_id: 28, device_comp_name: 'Battery', device_comp_color: 'Black', device_comp_description: 'Source of power for the device.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 43, device_version_id: 28, device_comp_name: 'System-on-a-Chip', device_comp_color: 'Black', device_comp_description: 'Processor that brings CPU and MODEM together.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 44, device_version_id: 28, device_comp_name: 'Memory card', device_comp_color: 'Black', device_comp_description: 'Stores memory on a device.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 45, device_version_id: 28, device_comp_name: 'Modem', device_comp_color: 'Black', device_comp_description: 'Communication component for receiving texts and calls.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 46, device_version_id: 28, device_comp_name: 'Camera', device_comp_color: 'Black', device_comp_description: 'Captures photographs and video.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 47, device_version_id: 28, device_comp_name: 'Sensor', device_comp_color: 'Black', device_comp_description: 'Enables touch-screen ability.', device_component_status_id: 1, device_comp_cost: 20)
DeviceComponent.create(id: 48, device_version_id: 28, device_comp_name: 'Processor', device_comp_color: 'Black', device_comp_description: 'Processes basic instructions that drive the device.', device_component_status_id: 1, device_comp_cost: 20)


DeviceColor.create(id: 1, color_name: 'Black')
DeviceColor.create(id: 2, color_name: 'White')
DeviceColor.create(id: 3, color_name: 'Gold')
DeviceColor.create(id: 4, color_name: 'Blue')
DeviceColor.create(id: 5, color_name: 'Grey')
DeviceColor.create(id: 6, color_name: 'Green')
DeviceColor.create(id: 7, color_name: 'Yellow')
DeviceColor.create(id: 8, color_name: 'Silver')
DeviceColor.create(id: 9, color_name: 'Orange')
DeviceColor.create(id: 10, color_name: 'Red')
DeviceColor.create(id: 11, color_name: 'Maroon')
DeviceColor.create(id: 12, color_name: 'Charcoal')

Technician.create(id: 1, tech_name: 'Jerry Higgenbottom', technician_status_id: 1, tech_expertise_notes: 'Master Technician 5+ years experience')
Technician.create(id: 2, tech_name: 'Daniel Whitman', technician_status_id: 1, tech_expertise_notes: 'Level 1 Technician 2+ years experience')

RepairOrderStatus.create(id: 1, repair_order_status: 'In Progress')
RepairOrderStatus.create(id: 2, repair_order_status: 'Not Started')
RepairOrderStatus.create(id: 3, repair_order_status: 'On Hold')
RepairOrderStatus.create(id: 4, repair_order_status: 'Awaiting Parts')
RepairOrderStatus.create(id: 5, repair_order_status: 'Completed')
RepairOrderStatus.create(id: 6, repair_order_status: 'Pick Up')

Customer.create(id: 1, customer_fname: 'Bradley', customer_lname: 'Sunnex', customer_email: 'bsunnex@gov.uk', customer_phone: '7132642222', customer_call: 0, customer_text: 1, customer_zip: '77520')
Customer.create(id: 2, customer_fname: 'Skipp', customer_lname: 'Kenefick', customer_email: 'skenefick@archive.org', customer_phone: '7139685623', customer_call: 1, customer_text: 1, customer_zip: '77521')
Customer.create(id: 3, customer_fname: 'Grethel', customer_lname: 'Boyels', customer_email: 'gboyles2@loc.gov', customer_phone: '28-6533504', customer_call: 1, customer_text: 0, customer_zip: '77521')
Customer.create(id: 4, customer_fname: 'Sherman', customer_lname: 'Itzhaiek', customer_email: 'sitzhaiek3@desdev', customer_phone: '8321416082', customer_call: 1, customer_text: 0, customer_zip: '77520')
Customer.create(id: 5, customer_fname: 'Cesare', customer_lname: 'Belsey', customer_email: 'cbelsey4@google.fr', customer_phone: '8327575070', customer_call: 1, customer_text: 0, customer_zip: '77520')
Customer.create(id: 6, customer_fname: 'Katrine', customer_lname: 'Gooderridge', customer_email: 'kgooderrige5@irs.gov', customer_phone: '7134601849', customer_call: 1, customer_text: 1, customer_zip: '77523')
Customer.create(id: 7, customer_fname: 'Joaquin', customer_lname: 'Yeatman', customer_email: 'jyeatman6@google.com', customer_phone: '2817828580', customer_call: 0, customer_text: 1, customer_zip: '77523')
Customer.create(id: 8, customer_fname: 'Konstatine', customer_lname: 'Oxford', customer_email: 'koxford1@gmail.com', customer_phone: '8321869219', customer_call: 1, customer_text: 1, customer_zip: '77522')
Customer.create(id: 9, customer_fname: 'Tally', customer_lname: 'Fosserd', customer_email: 'tfosserd8@rambler.com', customer_phone: '7132863965', customer_call: 1, customer_text: 1, customer_zip: '77520')
Customer.create(id: 10, customer_fname: 'Bonni', customer_lname: 'Moss', customer_email: 'Bmoss@gmail.com', customer_phone: '2812203297', customer_call: 1, customer_text: 1, customer_zip: '77522')



RepairOrder.create(id: 1, repair_order_date: '2018-08-01', repair_order_subtotal: 4 , repair_order_tax: '0.33' , repair_order_total: '4.33' , repair_order_accessories: 'None', repair_order_notes: 'Still awaiting parts', repair_order_status_id: 4, repair_order_status_date: '2018-08-01', customer_id: 1)
RepairOrder.create(id: 2, repair_order_date: '2018-07-10', repair_order_subtotal: 20 , repair_order_tax: '1.65' , repair_order_total: '21.65' , repair_order_accessories: 'None', repair_order_notes: 'Order has been completed', repair_order_status_id: 5, repair_order_status_date: '2018-07-25', customer_id: 2)
RepairOrder.create(id: 3, repair_order_date: '2018-04-15', repair_order_subtotal: 80 , repair_order_tax: '6.60' , repair_order_total: '86.60' , repair_order_accessories: 'Headphones', repair_order_notes: 'Order has not started', repair_order_status_id: 2, repair_order_status_date: '2018-04-18', customer_id: 3)
RepairOrder.create(id: 4, repair_order_date: '2018-02-14', repair_order_subtotal: 75 , repair_order_tax: '6.19' , repair_order_total: '81.19' , repair_order_accessories: 'None', repair_order_notes: 'Order is ready for pick up', repair_order_status_id: 6, repair_order_status_date: '2018-02-27', customer_id: 4)
RepairOrder.create(id: 5, repair_order_date: '2018-06-20', repair_order_subtotal: 10 , repair_order_tax: '0.83' , repair_order_total: '10.83' , repair_order_accessories: 'None', repair_order_notes: 'Order is ready for pick up', repair_order_status_id: 6, repair_order_status_date: '2018-06-27', customer_id: 5)
RepairOrder.create(id: 6, repair_order_date: '2018-05-18', repair_order_subtotal: 10 , repair_order_tax: '.83' , repair_order_total: '10.83' , repair_order_accessories: 'None', repair_order_notes: 'Order is ready for pick up', repair_order_status_id: 6, repair_order_status_date: '2018-05-22', customer_id: 6)
RepairOrder.create(id: 7, repair_order_date: '2018-05-27', repair_order_subtotal: 105 , repair_order_tax: '8.66' , repair_order_total: '113.66' , repair_order_accessories: 'None', repair_order_notes: 'Still awaiting parts', repair_order_status_id: 4, repair_order_status_date: '2018-06-03', customer_id: 7)
RepairOrder.create(id: 8, repair_order_date: '2018-07-12', repair_order_subtotal: 10 , repair_order_tax: '0.83' , repair_order_total: '10.83' , repair_order_accessories: 'None', repair_order_notes: 'Order is ready for pick up', repair_order_status_id: 6, repair_order_status_date: '2018-07-15', customer_id: 8)
RepairOrder.create(id: 9, repair_order_date: '2018-07-14', repair_order_subtotal: 10 , repair_order_tax: '0.83' , repair_order_total: '10.83' , repair_order_accessories: 'None', repair_order_notes: 'Order is ready for pick up', repair_order_status_id: 6, repair_order_status_date: '2018-07-18', customer_id: 9)
RepairOrder.create(id: 10, repair_order_date: '2018-01-23', repair_order_subtotal: 10 , repair_order_tax: '0.83' , repair_order_total: '10.83' , repair_order_accessories: 'None', repair_order_notes: 'Order is ready for pick up', repair_order_status_id: 6, repair_order_status_date: '2018-01-28', customer_id: 10)


Device.create(id: 1, imei_number: '113042453134555', device_color_id: 1, device_notes: 'N/A', repair_order_id: 1, device_version_id: 1)
Device.create(id: 2, imei_number: '180051685697655', device_color_id: 2, device_notes: 'N/A', repair_order_id: 2, device_version_id: 1)
Device.create(id: 3, imei_number: '152223651444976', device_color_id: 3, device_notes: 'N/A', repair_order_id: 3, device_version_id: 1)
Device.create(id: 4, imei_number: '147337459886407', device_color_id: 4, device_notes: 'N/A', repair_order_id: 4, device_version_id: 6)
Device.create(id: 5, imei_number: '150686872649352', device_color_id: 5, device_notes: 'N/A', repair_order_id: 5, device_version_id: 14)
Device.create(id: 6, imei_number: '191611445014518', device_color_id: 6, device_notes: 'N/A', repair_order_id: 6, device_version_id: 14)
Device.create(id: 7, imei_number: '109132608873576', device_color_id: 7, device_notes: 'N/A', repair_order_id: 7, device_version_id: 1)
Device.create(id: 8, imei_number: '177905355426150', device_color_id: 8, device_notes: 'N/A', repair_order_id: 8, device_version_id: 1)
Device.create(id: 9, imei_number: '189060307395062', device_color_id: 9, device_notes: 'N/A', repair_order_id: 9, device_version_id: 6)
Device.create(id: 10,imei_number: '169708478797738', device_color_id: 10, device_notes: 'N/A', repair_order_id: 10, device_version_id: 6)


RepairOrderItem.create(id: 1, device_component_id: 1, technician_id: 1, warranty_expire_date: '2018-08-01', warranty_coverage_notes: 'Repaired within 90 days.', repaired_as_warranty: 1, warranty_repair_date: '2018-05-01', price: 20 , device_id: 1, repair_order_status_id: 1)
RepairOrderItem.create(id: 2, device_component_id: 6, technician_id: 2, warranty_expire_date: '2018-09-01', warranty_coverage_notes: 'Repaired within 90 days.', repaired_as_warranty: 1, warranty_repair_date: '2018-06-01', price: 10,  device_id: 2, repair_order_status_id: 1)
RepairOrderItem.create(id: 3, device_component_id: 3, technician_id: 1, warranty_expire_date: '2018-10-01', warranty_coverage_notes: 'Repaired within 90 days.', repaired_as_warranty: 1, warranty_repair_date: '2018-07-01', price: 10, device_id: 3, repair_order_status_id: 1)
RepairOrderItem.create(id: 4, device_component_id: 8, technician_id: 2, warranty_expire_date: '2018-11-01', warranty_coverage_notes: 'Repaired within 90 days.', repaired_as_warranty: 1, warranty_repair_date: '2018-08-01', price: 10, device_id: 4, repair_order_status_id: 1)
RepairOrderItem.create(id: 5, device_component_id: 7, technician_id: 1, warranty_expire_date: '2018-12-01', warranty_coverage_notes: 'Repaired within 90 days.', repaired_as_warranty: 1, warranty_repair_date: '2018-09-01', price: 10, device_id: 5, repair_order_status_id: 1)
RepairOrderItem.create(id: 6, device_component_id: 2, technician_id: 1, warranty_expire_date: '2018-12-04', warranty_coverage_notes: 'Repaired within 90 days.', repaired_as_warranty: 1, warranty_repair_date: '2018-09-04', price: 10, device_id: 6, repair_order_status_id: 1)
RepairOrderItem.create(id: 7, device_component_id: 2, technician_id: 1, warranty_expire_date: '2018-10-09', warranty_coverage_notes: 'Repaired within 90 days.', repaired_as_warranty: 1, warranty_repair_date: '2018-07-09', price: 10, device_id: 7, repair_order_status_id: 1)
RepairOrderItem.create(id: 8, device_component_id: 1, technician_id: 2, warranty_expire_date: '2018-07-14', warranty_coverage_notes: 'Repaired within 90 days.', repaired_as_warranty: 1, warranty_repair_date: '2018-07-14', price: 10, device_id: 8, repair_order_status_id: 1)
RepairOrderItem.create(id: 9, device_component_id: 5, technician_id: 2, warranty_expire_date: '2018-04-03', warranty_coverage_notes: 'Repaired within 90 days.', repaired_as_warranty: 1, warranty_repair_date: '2018-01-03', price: 10, device_id: 9, repair_order_status_id: 1)
RepairOrderItem.create(id: 10, device_component_id: 7, technician_id: 1, warranty_expire_date: '2018-08-01', warranty_coverage_notes: 'Repaired within 90 days.', repaired_as_warranty: 1, warranty_repair_date: '2018-05-01', price: 10, device_id: 9, repair_order_status_id: 1)
RepairOrderItem.create(id: 11, device_component_id: 7, technician_id: 2, warranty_expire_date: '2018-08-01', warranty_coverage_notes: 'Repaired within 90 days.', repaired_as_warranty: 1, warranty_repair_date: '2018-05-01', price: 10, device_id: 10, repair_order_status_id: 1)
RepairOrderItem.create(id: 12, device_component_id: 8, technician_id: 1, warranty_expire_date: '2018-08-01', warranty_coverage_notes: 'Repaired within 90 days.', repaired_as_warranty: 1, warranty_repair_date: '2018-05-01', price: 10, device_id: 10, repair_order_status_id: 1)

Test.create(id: 1, test_name: 'Ringer', test_description: 'Tests whether the device ringer are functional.')
Test.create(id: 2, test_name: 'Speaker', test_description: 'Tests whether the device speaker are functional.')
Test.create(id: 3, test_name: 'Microphone', test_description: 'Tests whether the device speaker are functional.')
Test.create(id: 4, test_name: 'Vibrator', test_description: 'Tests whether the device speaker are functional.')
Test.create(id: 5, test_name: 'LED Light', test_description: 'Tests whether the device speaker are functional.')
Test.create(id: 6, test_name: 'Charging Port', test_description: 'Tests whether the device speaker are functional.')
Test.create(id: 7, test_name: 'Headphone Jack', test_description: 'Tests whether the device speaker are functional.')
Test.create(id: 8, test_name: 'Battery', test_description: 'Tests whether the device speaker are functional.')
Test.create(id: 9, test_name: 'Sim Card', test_description: 'Tests whether the device speaker are functional.')
Test.create(id: 10, test_name: 'Memory Card', test_description: 'Tests whether the device speaker are functional.')
Test.create(id: 11, test_name: 'Front Camera', test_description: 'Tests whether the device speaker are functional.')
Test.create(id: 12, test_name: 'Keypad Button', test_description: 'Tests whether the device speaker are functional.')
Test.create(id: 13, test_name: 'Power Button', test_description: 'Tests whether the device speaker are functional.')
Test.create(id: 14, test_name: 'Display/Screen', test_description: 'Tests whether the device speaker are functional.')



DevicePreTest.create(id: 1, device_id: 1, test_id: 1, pre_test_condition: 1)
DevicePreTest.create(id: 2, device_id: 1, test_id: 2, pre_test_condition: 1)
DevicePreTest.create(id: 3, device_id: 1, test_id: 3, pre_test_condition: 0)
DevicePreTest.create(id: 4, device_id: 1, test_id: 4, pre_test_condition: 1)
DevicePreTest.create(id: 5, device_id: 1, test_id: 5, pre_test_condition: 1)
DevicePreTest.create(id: 6, device_id: 1, test_id: 6, pre_test_condition: 1)
DevicePreTest.create(id: 7, device_id: 1, test_id: 7, pre_test_condition: 1)
DevicePreTest.create(id: 8, device_id: 1, test_id: 8, pre_test_condition: 1)
DevicePreTest.create(id: 9, device_id: 1, test_id: 9, pre_test_condition: 1)
DevicePreTest.create(id: 10, device_id: 1, test_id: 9, pre_test_condition: 1)
DevicePreTest.create(id: 11, device_id: 1, test_id: 10, pre_test_condition: 1)
DevicePreTest.create(id: 12, device_id: 1, test_id: 12, pre_test_condition: 1)
DevicePreTest.create(id: 13, device_id: 1, test_id: 13, pre_test_condition: 1)
DevicePreTest.create(id: 14, device_id: 1, test_id: 14, pre_test_condition: 1)
DevicePreTest.create(id: 15, device_id: 2, test_id: 15, pre_test_condition: 1)
DevicePreTest.create(id: 16, device_id: 2, test_id: 16, pre_test_condition: 1)
DevicePreTest.create(id: 17, device_id: 2, test_id: 17, pre_test_condition: 1)
DevicePreTest.create(id: 18, device_id: 2, test_id: 18, pre_test_condition: 1)
DevicePreTest.create(id: 19, device_id: 2, test_id: 19, pre_test_condition: 1)
DevicePreTest.create(id: 20, device_id: 2, test_id: 20, pre_test_condition: 1)
DevicePreTest.create(id: 21, device_id: 2, test_id: 21, pre_test_condition: 1)
DevicePreTest.create(id: 22, device_id: 2, test_id: 22, pre_test_condition: 1)
DevicePreTest.create(id: 23, device_id: 2, test_id: 23, pre_test_condition: 0)
DevicePreTest.create(id: 24, device_id: 2, test_id: 24, pre_test_condition: 1)
DevicePreTest.create(id: 25, device_id: 2, test_id: 25, pre_test_condition: 1)
DevicePreTest.create(id: 26, device_id: 2, test_id: 26, pre_test_condition: 1)
DevicePreTest.create(id: 27, device_id: 2, test_id: 27, pre_test_condition: 1)
DevicePreTest.create(id: 28, device_id: 2, test_id: 28, pre_test_condition: 1)
DevicePreTest.create(id: 29, device_id: 3, test_id: 29, pre_test_condition: 1)
DevicePreTest.create(id: 30, device_id: 3, test_id: 30, pre_test_condition: 1)
DevicePreTest.create(id: 31, device_id: 3, test_id: 31, pre_test_condition: 1)
DevicePreTest.create(id: 32, device_id: 3, test_id: 32, pre_test_condition: 1)
DevicePreTest.create(id: 33, device_id: 3, test_id: 33, pre_test_condition: 0)
DevicePreTest.create(id: 34, device_id: 3, test_id: 34, pre_test_condition: 1)
DevicePreTest.create(id: 35, device_id: 3, test_id: 35, pre_test_condition: 1)
DevicePreTest.create(id: 36, device_id: 3, test_id: 36, pre_test_condition: 1)
DevicePreTest.create(id: 37, device_id: 3, test_id: 37, pre_test_condition: 1)
DevicePreTest.create(id: 38, device_id: 3, test_id: 38, pre_test_condition: 1)
DevicePreTest.create(id: 39, device_id: 3, test_id: 39, pre_test_condition: 1)
DevicePreTest.create(id: 40, device_id: 3, test_id: 40, pre_test_condition: 1)
DevicePreTest.create(id: 41, device_id: 3, test_id: 41, pre_test_condition: 1)
DevicePreTest.create(id: 42, device_id: 3, test_id: 42, pre_test_condition: 1)
DevicePreTest.create(id: 43, device_id: 4, test_id: 43, pre_test_condition: 1)
DevicePreTest.create(id: 44, device_id: 4, test_id: 44, pre_test_condition: 1)
DevicePreTest.create(id: 45, device_id: 4, test_id: 45, pre_test_condition: 1)
DevicePreTest.create(id: 46, device_id: 4, test_id: 46, pre_test_condition: 1)
DevicePreTest.create(id: 47, device_id: 4, test_id: 47, pre_test_condition: 1)
DevicePreTest.create(id: 48, device_id: 4, test_id: 48, pre_test_condition: 1)
DevicePreTest.create(id: 49, device_id: 4, test_id: 49, pre_test_condition: 1)
DevicePreTest.create(id: 50, device_id: 4, test_id: 50, pre_test_condition: 1)
DevicePreTest.create(id: 51, device_id: 4, test_id: 51, pre_test_condition: 0)
DevicePreTest.create(id: 52, device_id: 4, test_id: 52, pre_test_condition: 1)
DevicePreTest.create(id: 53, device_id: 4, test_id: 53, pre_test_condition: 1)
DevicePreTest.create(id: 54, device_id: 4, test_id: 54, pre_test_condition: 1)
DevicePreTest.create(id: 55, device_id: 4, test_id: 55, pre_test_condition: 1)
DevicePreTest.create(id: 56, device_id: 4, test_id: 56, pre_test_condition: 1)
DevicePreTest.create(id: 57, device_id: 5, test_id: 57, pre_test_condition: 1)
DevicePreTest.create(id: 58, device_id: 5, test_id: 58, pre_test_condition: 1)
DevicePreTest.create(id: 59, device_id: 5, test_id: 59, pre_test_condition: 1)
DevicePreTest.create(id: 60, device_id: 5, test_id: 60, pre_test_condition: 1)
DevicePreTest.create(id: 61, device_id: 5, test_id: 61, pre_test_condition: 1)
DevicePreTest.create(id: 62, device_id: 5, test_id: 62, pre_test_condition: 1)
DevicePreTest.create(id: 63, device_id: 5, test_id: 63, pre_test_condition: 1)
DevicePreTest.create(id: 64, device_id: 5, test_id: 64, pre_test_condition: 1)
DevicePreTest.create(id: 65, device_id: 5, test_id: 65, pre_test_condition: 1)
DevicePreTest.create(id: 66, device_id: 5, test_id: 66, pre_test_condition: 0)
DevicePreTest.create(id: 67, device_id: 5, test_id: 67, pre_test_condition: 1)
DevicePreTest.create(id: 68, device_id: 5, test_id: 68, pre_test_condition: 1)
DevicePreTest.create(id: 69, device_id: 5, test_id: 69, pre_test_condition: 1)
DevicePreTest.create(id: 70, device_id: 5, test_id: 70, pre_test_condition: 1)
DevicePreTest.create(id: 71, device_id: 6, test_id: 71, pre_test_condition: 1)
DevicePreTest.create(id: 72, device_id: 6, test_id: 72, pre_test_condition: 1)
DevicePreTest.create(id: 73, device_id: 6, test_id: 73, pre_test_condition: 1)
DevicePreTest.create(id: 74, device_id: 6, test_id: 74, pre_test_condition: 1)
DevicePreTest.create(id: 75, device_id: 6, test_id: 75, pre_test_condition: 1)
DevicePreTest.create(id: 76, device_id: 6, test_id: 76, pre_test_condition: 1)
DevicePreTest.create(id: 77, device_id: 6, test_id: 77, pre_test_condition: 1)
DevicePreTest.create(id: 78, device_id: 6, test_id: 78, pre_test_condition: 1)
DevicePreTest.create(id: 79, device_id: 6, test_id: 79, pre_test_condition: 1)
DevicePreTest.create(id: 80, device_id: 6, test_id: 80, pre_test_condition: 0)
DevicePreTest.create(id: 81, device_id: 6, test_id: 81, pre_test_condition: 1)
DevicePreTest.create(id: 82, device_id: 6, test_id: 82, pre_test_condition: 1)
DevicePreTest.create(id: 83, device_id: 6, test_id: 83, pre_test_condition: 1)
DevicePreTest.create(id: 84, device_id: 6, test_id: 84, pre_test_condition: 1)
DevicePreTest.create(id: 85, device_id: 7, test_id: 85, pre_test_condition: 1)
DevicePreTest.create(id: 86, device_id: 7, test_id: 86, pre_test_condition: 1)
DevicePreTest.create(id: 87, device_id: 7, test_id: 87, pre_test_condition: 1)
DevicePreTest.create(id: 88, device_id: 7, test_id: 88, pre_test_condition: 1)
DevicePreTest.create(id: 89, device_id: 7, test_id: 89, pre_test_condition: 0)
DevicePreTest.create(id: 90, device_id: 7, test_id: 90, pre_test_condition: 1)
DevicePreTest.create(id: 91, device_id: 7, test_id: 91, pre_test_condition: 1)
DevicePreTest.create(id: 92, device_id: 7, test_id: 92, pre_test_condition: 1)
DevicePreTest.create(id: 93, device_id: 7, test_id: 93, pre_test_condition: 1)
DevicePreTest.create(id: 94, device_id: 7, test_id: 94, pre_test_condition: 1)
DevicePreTest.create(id: 95, device_id: 7, test_id: 95, pre_test_condition: 1)
DevicePreTest.create(id: 96, device_id: 7, test_id: 96, pre_test_condition: 1)
DevicePreTest.create(id: 97, device_id: 7, test_id: 97, pre_test_condition: 1)
DevicePreTest.create(id: 98, device_id: 7, test_id: 98, pre_test_condition: 1)
DevicePreTest.create(id: 99, device_id: 8, test_id: 99, pre_test_condition: 1)
DevicePreTest.create(id: 100, device_id: 8, test_id: 100, pre_test_condition: 1)
DevicePreTest.create(id: 101, device_id: 8, test_id: 101, pre_test_condition: 1)
DevicePreTest.create(id: 102, device_id: 8, test_id: 102, pre_test_condition: 1)
DevicePreTest.create(id: 103, device_id: 8, test_id: 103, pre_test_condition: 1)
DevicePreTest.create(id: 104, device_id: 8, test_id: 104, pre_test_condition: 0)
DevicePreTest.create(id: 105, device_id: 8, test_id: 105, pre_test_condition: 1)
DevicePreTest.create(id: 106, device_id: 8, test_id: 106, pre_test_condition: 1)
DevicePreTest.create(id: 107, device_id: 8, test_id: 107, pre_test_condition: 1)
DevicePreTest.create(id: 108, device_id: 8, test_id: 108, pre_test_condition: 1)
DevicePreTest.create(id: 109, device_id: 8, test_id: 109, pre_test_condition: 1)
DevicePreTest.create(id: 110, device_id: 8, test_id: 110, pre_test_condition: 1)
DevicePreTest.create(id: 111, device_id: 9, test_id: 111, pre_test_condition: 1)
DevicePreTest.create(id: 112, device_id: 9, test_id: 112, pre_test_condition: 1)
DevicePreTest.create(id: 113, device_id: 9, test_id: 113, pre_test_condition: 1)
DevicePreTest.create(id: 114, device_id: 9, test_id: 114, pre_test_condition: 1)
DevicePreTest.create(id: 115, device_id: 9, test_id: 115, pre_test_condition: 1)
DevicePreTest.create(id: 116, device_id: 9, test_id: 116, pre_test_condition: 0)
DevicePreTest.create(id: 117, device_id: 9, test_id: 117, pre_test_condition: 1)
DevicePreTest.create(id: 118, device_id: 9, test_id: 118, pre_test_condition: 1)
DevicePreTest.create(id: 119, device_id: 9, test_id: 119, pre_test_condition: 1)
DevicePreTest.create(id: 120, device_id: 9, test_id: 120, pre_test_condition: 1)
DevicePreTest.create(id: 121, device_id: 9, test_id: 121, pre_test_condition: 1)
DevicePreTest.create(id: 122, device_id: 9, test_id: 122, pre_test_condition: 1)
DevicePreTest.create(id: 123, device_id: 9, test_id: 123, pre_test_condition: 1)
DevicePreTest.create(id: 124, device_id: 9, test_id: 124, pre_test_condition: 1)
DevicePreTest.create(id: 125, device_id: 10, test_id: 125, pre_test_condition: 1)
DevicePreTest.create(id: 126, device_id: 10, test_id: 126, pre_test_condition: 1)
DevicePreTest.create(id: 127, device_id: 10, test_id: 127, pre_test_condition: 1)
DevicePreTest.create(id: 128, device_id: 10, test_id: 128, pre_test_condition: 1)
DevicePreTest.create(id: 129, device_id: 10, test_id: 129, pre_test_condition: 0)
DevicePreTest.create(id: 130, device_id: 10, test_id: 130, pre_test_condition: 1)
DevicePreTest.create(id: 131, device_id: 10, test_id: 131, pre_test_condition: 1)
DevicePreTest.create(id: 132, device_id: 10, test_id: 132, pre_test_condition: 1)
DevicePreTest.create(id: 133, device_id: 10, test_id: 133, pre_test_condition: 1)
DevicePreTest.create(id: 134, device_id: 10, test_id: 134, pre_test_condition: 1)
DevicePreTest.create(id: 135, device_id: 10, test_id: 135, pre_test_condition: 1)
DevicePreTest.create(id: 136, device_id: 10, test_id: 136, pre_test_condition: 1)
DevicePreTest.create(id: 137, device_id: 10, test_id: 137, pre_test_condition: 1)
DevicePreTest.create(id: 138, device_id: 10, test_id: 138, pre_test_condition: 1)
DevicePreTest.create(id: 139, device_id: 8, test_id: 139, pre_test_condition: 1)
DevicePreTest.create(id: 140, device_id: 8, test_id: 140, pre_test_condition: 1)

DevicePostTest.create(id: 1, device_id: 1, test_id: 1, post_test_condition: 1)
DevicePostTest.create(id: 2, device_id: 1, test_id: 2, post_test_condition: 1)
DevicePostTest.create(id: 3, device_id: 1, test_id: 3, post_test_condition: 1)
DevicePostTest.create(id: 4, device_id: 1, test_id: 4, post_test_condition: 1)
DevicePostTest.create(id: 5, device_id: 1, test_id: 5, post_test_condition: 1)
DevicePostTest.create(id: 6, device_id: 1, test_id: 6, post_test_condition: 1)
DevicePostTest.create(id: 7, device_id: 1, test_id: 7, post_test_condition: 1)
DevicePostTest.create(id: 8, device_id: 1, test_id: 8, post_test_condition: 1)
DevicePostTest.create(id: 9, device_id: 1, test_id: 9, post_test_condition: 1)
DevicePostTest.create(id: 10, device_id: 1, test_id: 9, post_test_condition: 1)
DevicePostTest.create(id: 11, device_id: 1, test_id: 10, post_test_condition: 1)
DevicePostTest.create(id: 12, device_id: 1, test_id: 12, post_test_condition: 1)
DevicePostTest.create(id: 13, device_id: 1, test_id: 13, post_test_condition: 1)
DevicePostTest.create(id: 14, device_id: 1, test_id: 14, post_test_condition: 1)
DevicePostTest.create(id: 15, device_id: 2, test_id: 15, post_test_condition: 1)
DevicePostTest.create(id: 16, device_id: 2, test_id: 16, post_test_condition: 1)
DevicePostTest.create(id: 17, device_id: 2, test_id: 17, post_test_condition: 1)
DevicePostTest.create(id: 18, device_id: 2, test_id: 18, post_test_condition: 1)
DevicePostTest.create(id: 19, device_id: 2, test_id: 19, post_test_condition: 1)
DevicePostTest.create(id: 20, device_id: 2, test_id: 20, post_test_condition: 1)
DevicePostTest.create(id: 21, device_id: 2, test_id: 21, post_test_condition: 1)
DevicePostTest.create(id: 22, device_id: 2, test_id: 22, post_test_condition: 1)
DevicePostTest.create(id: 23, device_id: 2, test_id: 23, post_test_condition: 1)
DevicePostTest.create(id: 24, device_id: 2, test_id: 24, post_test_condition: 1)
DevicePostTest.create(id: 25, device_id: 2, test_id: 25, post_test_condition: 1)
DevicePostTest.create(id: 26, device_id: 2, test_id: 26, post_test_condition: 1)
DevicePostTest.create(id: 27, device_id: 2, test_id: 27, post_test_condition: 1)
DevicePostTest.create(id: 28, device_id: 2, test_id: 28, post_test_condition: 1)
DevicePostTest.create(id: 29, device_id: 3, test_id: 29, post_test_condition: 1)
DevicePostTest.create(id: 30, device_id: 3, test_id: 30, post_test_condition: 1)
DevicePostTest.create(id: 31, device_id: 3, test_id: 31, post_test_condition: 1)
DevicePostTest.create(id: 32, device_id: 3, test_id: 32, post_test_condition: 1)
DevicePostTest.create(id: 33, device_id: 3, test_id: 33, post_test_condition: 1)
DevicePostTest.create(id: 34, device_id: 3, test_id: 34, post_test_condition: 1)
DevicePostTest.create(id: 35, device_id: 3, test_id: 35, post_test_condition: 1)
DevicePostTest.create(id: 36, device_id: 3, test_id: 36, post_test_condition: 1)
DevicePostTest.create(id: 37, device_id: 3, test_id: 37, post_test_condition: 1)
DevicePostTest.create(id: 38, device_id: 3, test_id: 38, post_test_condition: 1)
DevicePostTest.create(id: 39, device_id: 3, test_id: 39, post_test_condition: 1)
DevicePostTest.create(id: 40, device_id: 3, test_id: 40, post_test_condition: 1)
DevicePostTest.create(id: 41, device_id: 3, test_id: 41, post_test_condition: 1)
DevicePostTest.create(id: 42, device_id: 3, test_id: 42, post_test_condition: 1)
DevicePostTest.create(id: 43, device_id: 4, test_id: 43, post_test_condition: 1)
DevicePostTest.create(id: 44, device_id: 4, test_id: 44, post_test_condition: 1)
DevicePostTest.create(id: 45, device_id: 4, test_id: 45, post_test_condition: 1)
DevicePostTest.create(id: 46, device_id: 4, test_id: 46, post_test_condition: 1)
DevicePostTest.create(id: 47, device_id: 4, test_id: 47, post_test_condition: 1)
DevicePostTest.create(id: 48, device_id: 4, test_id: 48, post_test_condition: 1)
DevicePostTest.create(id: 49, device_id: 4, test_id: 49, post_test_condition: 1)
DevicePostTest.create(id: 50, device_id: 4, test_id: 50, post_test_condition: 1)
DevicePostTest.create(id: 51, device_id: 4, test_id: 51, post_test_condition: 1)
DevicePostTest.create(id: 52, device_id: 4, test_id: 52, post_test_condition: 1)
DevicePostTest.create(id: 53, device_id: 4, test_id: 53, post_test_condition: 1)
DevicePostTest.create(id: 54, device_id: 4, test_id: 54, post_test_condition: 1)
DevicePostTest.create(id: 55, device_id: 4, test_id: 55, post_test_condition: 1)
DevicePostTest.create(id: 56, device_id: 4, test_id: 56, post_test_condition: 1)
DevicePostTest.create(id: 57, device_id: 5, test_id: 57, post_test_condition: 1)
DevicePostTest.create(id: 58, device_id: 5, test_id: 58, post_test_condition: 1)
DevicePostTest.create(id: 59, device_id: 5, test_id: 59, post_test_condition: 1)
DevicePostTest.create(id: 60, device_id: 5, test_id: 60, post_test_condition: 1)
DevicePostTest.create(id: 61, device_id: 5, test_id: 61, post_test_condition: 1)
DevicePostTest.create(id: 62, device_id: 5, test_id: 62, post_test_condition: 1)
DevicePostTest.create(id: 63, device_id: 5, test_id: 63, post_test_condition: 1)
DevicePostTest.create(id: 64, device_id: 5, test_id: 64, post_test_condition: 1)
DevicePostTest.create(id: 65, device_id: 5, test_id: 65, post_test_condition: 1)
DevicePostTest.create(id: 66, device_id: 5, test_id: 66, post_test_condition: 1)
DevicePostTest.create(id: 67, device_id: 5, test_id: 67, post_test_condition: 1)
DevicePostTest.create(id: 68, device_id: 5, test_id: 68, post_test_condition: 1)
DevicePostTest.create(id: 69, device_id: 5, test_id: 69, post_test_condition: 1)
DevicePostTest.create(id: 70, device_id: 5, test_id: 70, post_test_condition: 1)
DevicePostTest.create(id: 71, device_id: 6, test_id: 71, post_test_condition: 1)
DevicePostTest.create(id: 72, device_id: 6, test_id: 72, post_test_condition: 1)
DevicePostTest.create(id: 73, device_id: 6, test_id: 73, post_test_condition: 1)
DevicePostTest.create(id: 74, device_id: 6, test_id: 74, post_test_condition: 1)
DevicePostTest.create(id: 75, device_id: 6, test_id: 75, post_test_condition: 1)
DevicePostTest.create(id: 76, device_id: 6, test_id: 76, post_test_condition: 1)
DevicePostTest.create(id: 77, device_id: 6, test_id: 77, post_test_condition: 1)
DevicePostTest.create(id: 78, device_id: 6, test_id: 78, post_test_condition: 1)
DevicePostTest.create(id: 79, device_id: 6, test_id: 79, post_test_condition: 1)
DevicePostTest.create(id: 80, device_id: 6, test_id: 80, post_test_condition: 1)
DevicePostTest.create(id: 81, device_id: 6, test_id: 81, post_test_condition: 1)
DevicePostTest.create(id: 82, device_id: 6, test_id: 82, post_test_condition: 1)
DevicePostTest.create(id: 83, device_id: 6, test_id: 83, post_test_condition: 1)
DevicePostTest.create(id: 84, device_id: 6, test_id: 84, post_test_condition: 1)
DevicePostTest.create(id: 85, device_id: 7, test_id: 85, post_test_condition: 1)
DevicePostTest.create(id: 86, device_id: 7, test_id: 86, post_test_condition: 1)
DevicePostTest.create(id: 87, device_id: 7, test_id: 87, post_test_condition: 1)
DevicePostTest.create(id: 88, device_id: 7, test_id: 88, post_test_condition: 1)
DevicePostTest.create(id: 89, device_id: 7, test_id: 89, post_test_condition: 1)
DevicePostTest.create(id: 90, device_id: 7, test_id: 90, post_test_condition: 1)
DevicePostTest.create(id: 91, device_id: 7, test_id: 91, post_test_condition: 1)
DevicePostTest.create(id: 92, device_id: 7, test_id: 92, post_test_condition: 1)
DevicePostTest.create(id: 93, device_id: 7, test_id: 93, post_test_condition: 1)
DevicePostTest.create(id: 94, device_id: 7, test_id: 94, post_test_condition: 1)
DevicePostTest.create(id: 95, device_id: 7, test_id: 95, post_test_condition: 1)
DevicePostTest.create(id: 96, device_id: 7, test_id: 96, post_test_condition: 1)
DevicePostTest.create(id: 97, device_id: 7, test_id: 97, post_test_condition: 1)
DevicePostTest.create(id: 98, device_id: 7, test_id: 98, post_test_condition: 1)
DevicePostTest.create(id: 99, device_id: 8, test_id: 99, post_test_condition: 1)
DevicePostTest.create(id: 100, device_id: 8, test_id: 100, post_test_condition: 1)
DevicePostTest.create(id: 101, device_id: 8, test_id: 101, post_test_condition: 1)
DevicePostTest.create(id: 102, device_id: 8, test_id: 102, post_test_condition: 1)
DevicePostTest.create(id: 103, device_id: 8, test_id: 103, post_test_condition: 1)
DevicePostTest.create(id: 104, device_id: 8, test_id: 104, post_test_condition: 1)
DevicePostTest.create(id: 105, device_id: 8, test_id: 105, post_test_condition: 1)
DevicePostTest.create(id: 106, device_id: 8, test_id: 106, post_test_condition: 1)
DevicePostTest.create(id: 107, device_id: 8, test_id: 107, post_test_condition: 1)
DevicePostTest.create(id: 108, device_id: 8, test_id: 108, post_test_condition: 1)
DevicePostTest.create(id: 109, device_id: 8, test_id: 109, post_test_condition: 1)
DevicePostTest.create(id: 110, device_id: 8, test_id: 110, post_test_condition: 1)
DevicePostTest.create(id: 111, device_id: 9, test_id: 111, post_test_condition: 1)
DevicePostTest.create(id: 112, device_id: 9, test_id: 112, post_test_condition: 1)
DevicePostTest.create(id: 113, device_id: 9, test_id: 113, post_test_condition: 1)
DevicePostTest.create(id: 114, device_id: 9, test_id: 114, post_test_condition: 1)
DevicePostTest.create(id: 115, device_id: 9, test_id: 115, post_test_condition: 1)
DevicePostTest.create(id: 116, device_id: 9, test_id: 116, post_test_condition: 1)
DevicePostTest.create(id: 117, device_id: 9, test_id: 117, post_test_condition: 1)
DevicePostTest.create(id: 118, device_id: 9, test_id: 118, post_test_condition: 1)
DevicePostTest.create(id: 119, device_id: 9, test_id: 119, post_test_condition: 1)
DevicePostTest.create(id: 120, device_id: 9, test_id: 120, post_test_condition: 1)
DevicePostTest.create(id: 121, device_id: 9, test_id: 121, post_test_condition: 1)
DevicePostTest.create(id: 122, device_id: 9, test_id: 122, post_test_condition: 1)
DevicePostTest.create(id: 123, device_id: 9, test_id: 123, post_test_condition: 1)
DevicePostTest.create(id: 124, device_id: 9, test_id: 124, post_test_condition: 1)
DevicePostTest.create(id: 125, device_id: 10, test_id: 125, post_test_condition: 1)
DevicePostTest.create(id: 126, device_id: 10, test_id: 126, post_test_condition: 1)
DevicePostTest.create(id: 127, device_id: 10, test_id: 127, post_test_condition: 1)
DevicePostTest.create(id: 128, device_id: 10, test_id: 128, post_test_condition: 1)
DevicePostTest.create(id: 129, device_id: 10, test_id: 129, post_test_condition: 1)
DevicePostTest.create(id: 130, device_id: 10, test_id: 130, post_test_condition: 1)
DevicePostTest.create(id: 131, device_id: 10, test_id: 131, post_test_condition: 1)
DevicePostTest.create(id: 132, device_id: 10, test_id: 132, post_test_condition: 1)
DevicePostTest.create(id: 133, device_id: 10, test_id: 133, post_test_condition: 1)
DevicePostTest.create(id: 134, device_id: 10, test_id: 134, post_test_condition: 1)
DevicePostTest.create(id: 135, device_id: 10, test_id: 135, post_test_condition: 1)
DevicePostTest.create(id: 136, device_id: 10, test_id: 136, post_test_condition: 1)
DevicePostTest.create(id: 137, device_id: 10, test_id: 137, post_test_condition: 1)
DevicePostTest.create(id: 138, device_id: 10, test_id: 138, post_test_condition: 1)
DevicePostTest.create(id: 139, device_id: 8, test_id: 139, post_test_condition: 1)
DevicePostTest.create(id: 140, device_id: 8, test_id: 140, post_test_condition: 1)








